# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :upload_prod do
    
    build_app
    
    upload_to_testflight
  end

  desc "Distribute to Firebase iOS qa-team"
  lane :upload_staging do
      build_ios_app
      # build_ios_app is a built-in fastlane action.

      firebase_app_distribution(
          app: "1:877450017629:ios:a6fc83be07a91ae5e4c6b4",
          firebase_cli_token: "1//03JT2Sa4V4aFVCgYIARAAGAMSNwF-L9IrChHQgVjWPmXLeEflpjDmBib24poocHPbunII0JmQtIfDG6mstBsE2NOzUUwUs1840Zo",
          groups: "qa-team",
          release_notes: "Lots of amazing new features to test out!"
      )

  end

end

